export class ListStyle{

    static readonly LIST_WIDTH: string = "100%";

    static readonly LIST_HEIGHT: string = "100%";

    static readonly LIST_ITEM_MARGIN_TOP: number = 15;

    static readonly LIST_ITEM_WIDTH: string = "90%";

    static readonly LIST_ITEM_BORDER_RADIUS: string = "5%";

    static readonly LIST_ITEM_PADDING: number = 15;
}

export class NewsItemStyle{
    static readonly SPACE_BETWEEN_TITLE_AND_DATE: number = 10;

    static readonly SPACE_BETWEEN_DATE_AND_AUTHOR: number = 30;

    static readonly TITLE_FONT_SIZE: number = 18;

    static readonly DATE_AND_AUTHOR_FONT_SIZE: number = 14;
}