import { StartupTask } from '@kit.AbilityKit';

export class UserPageComponentStyle{
    static readonly PAGE_WIDTH: string = "90%"

    static readonly PAGE_HEIGHT: string = "90%"
}

export class UserNewsCollectionComponentStyle{
    static readonly COMPONENT_HEIGHT: number = 150;

    static readonly COMPONENT_BORDER_RADIUS: string = '5%';

    static readonly COMPONENT_PADDING: Padding ={top:"5%", bottom: "5%"};

    static readonly COLUMN_SPACE: number = 20;

    static readonly COLUMN_WIDTH: string = "90%"

    static readonly EACH_ROW_WIDTH: string = "95%";

    static readonly ICON_HEIGHT: number = 25;

    static readonly NAV_DEST_WIDTH: string = "100%";

    static readonly NAV_DEST_HEIGHT: string = "100%";
}